name: Build libmpv-android

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

permissions:
  contents: write

env:
  NDK_VER: 25.1.8937393

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Symlink SDK
        working-directory: ./buildscripts
        run: |
          mkdir sdk
          ln -s ${ANDROID_HOME} ./sdk/android-sdk-linux
      - name: Bundle (default)
        working-directory: ./buildscripts
        run: |
          sudo chmod +x bundle_default.sh
          ./bundle_default.sh
      - name: Bundle (full)
        working-directory: ./buildscripts
        run: |
          sudo chmod +x bundle_full.sh
          ./bundle_full.sh
      - name: Bundle (encoders-gpl)
        working-directory: ./buildscripts
        run: |
          sudo chmod +x bundle_encoders-gpl.sh
          ./bundle_encoders-gpl.sh
      - uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: /home/runner/work/libmpv-android-video-build/libmpv-android-video-build/buildscripts/*.jar
      - uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          draft: true
          prerelease: false
          tag_name: "vnext"
          files: |
            /home/runner/work/libmpv-android-video-build/libmpv-android-video-build/buildscripts/*.jar
