name: Build libmpv-android

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Symlink SDK
        working-directory: ./buildscripts
        run: |
          mkdir sdk
          ln -s ${ANDROID_HOME} ./sdk/android-sdk-linux
      - name: Bundle (default)
        working-directory: ./buildscripts
        run: |
          sudo chmod +x bundle_default.sh
          ./bundle_default.sh
      # TODO(alexmercerind): Figure out this shit.
      # - name: Bundle (full)
      #   working-directory: ./buildscripts
      #   run: |
      #     sudo chmod +x bundle_full.sh
      #     ./bundle_full.sh
      # - name: Bundle (encoders-gpl)
      #   working-directory: ./buildscripts
      #   run: |
      #     sudo chmod +x bundle_encoders-gpl.sh
      #     ./bundle_encoders-gpl.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: |
            ./buildscripts/*.jar
            ./buildscripts/deps/media-kit-android-helper/app/build/outputs/apk/release/*.jar
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          draft: true
          prerelease: false
          tag_name: "vnext"
          files: |
            buildscripts/*.zip
            buildscripts/deps/media-kit-android-helper/app/build/outputs/apk/release/*.jar
